name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          config_timezone: America/Detroit
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_languages: no
          plugin_languages_ignored: >-
            html, css, less, dockerfile, qmake, lex, cmake, shaderlab
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
